on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 SFTP uploader                       # Upload to SFTP
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: access878234082.webspace-data.io      # Recommended to put the credentials in github secrets.
          username: u734623326
          password: ${{ secrets.FTP_PASSWORD }}
          compress: true                             # Compression
          localDir: '.'                              # Required, Absolute or relative to cwd.
          remoteDir: '/clickandbuilds/StagingInterazioniUmane/'                             # Required, Absolute path only.
          exclude: '.git*,.DS_Store,wp-config.php,wp-content/uploads,wp-content/wp-includes,wp-content/wp-admin'                 # Optional. exclude patterns (glob) like .gitignore, use ',' to split, Default to ''.
